/*Creacion de la base de datos*/
CREATE DATABASE MBShop;
USE MBShop;

/*      TABLAS      */

/*Creacion de la tabla de facturas*/
CREATE TABLE  USUARIOS
(
    CODIGO BIGINT PRIMARY KEY ,
    CODIGO_C BIGINT 
    NOMBRE_USUARIO VARCHAR(30) NOT NULL,
    CONTRASENA VARCHAR(30) NOT NULL
);

/* Creacion tabla de productos*/
CREATE TABLE PRODUCTOS
(   
    NOMBRE_PROD VARCHAR(20) PRIMARY KEY,
    PRECIO_PROD BIGINT NOT NULL,
    CANTIDAD_PROD BIGINT NOT NULL,
    DESCRIPCION_PROD VARCHAR(200),
    FKCODIGO BIGINT NOT NULL,
    ESTADO VARCHAR (10) NOT NULL
);

/* Creacion tabla de produtos*/
CREATE TABLE VENTAS
(   
    NUM_VENTA BIGINT PRIMARY KEY AUTO_INCREMENT,
    FKNOMBRE_PROD VARCHAR(20) NOT NULL,
    FKCODIGO1 BIGINT NOT NULL,
    CANTIDAD_VEND BIGINT NOT NULL
);

/* Creacion tabla de whislist*/
CREATE TABLE LISTA_DE_DESEOS
(
    CONTADOR_ART BIGINT PRIMARY KEY,
    FKNOMBRE_PROD1 VARCHAR(20) NOT NULL,
    FKCODIGO2 BIGINT NOT NULL
);

/* Creacion tabla de compras*/
CREATE TABLE COMPRAS
(
    CONTADOR_COMPRAS BIGINT PRIMARY KEY,
    FKNOMBRE_PROD2 VARCHAR(20) NOT NULL,
    FKCODIGO3 BIGINT NOT NULL
);
/*      CLAVES DE ACCESO        */

/*definicion FOREIGN KEY PRODUCTOS*/
ALTER TABLE PRODUCTOS
ADD
CONSTRAINT FK_CONT_USUA FOREIGN KEY(FKCODIGO)
REFERENCES USUARIOS (CODIGO);

/*definicion FOREIGN KEY VENTAS*/
ALTER TABLE VENTAS
ADD
CONSTRAINT FK_CONT_USUA1 FOREIGN KEY(FKCODIGO1)
REFERENCES USUARIOS (CODIGO);

ALTER TABLE VENTAS
ADD
CONSTRAINT FK_CONT_PROD FOREIGN KEY(FKNOMBRE_PROD)
REFERENCES PRODUCTOS (NOMBRE_PROD);

/*definicion FOREIGN KEY WISHLIST*/
ALTER TABLE LISTA_DE_DESEOS
ADD
CONSTRAINT K_CONT_USUA2 FOREIGN KEY(FKCODIGO2)
REFERENCES USUARIOS (CODIGO);

ALTER TABLE LISTA_DE_DESEOS
ADD
CONSTRAINT FK_CONT_PROD1 FOREIGN KEY (FKNOMBRE_PROD1)
REFERENCES PRODUCTOS (NOMBRE_PROD);

/*definicion FOREIGN KEY COMPRAS*/
ALTER TABLE COMPRAS
ADD
CONSTRAINT FK_CONT_USUA3 FOREIGN KEY(FKCODIGO3)
REFERENCES USUARIOS (CODIGO);

ALTER TABLE COMPRAS 
ADD
CONSTRAINT FK_CONT_PROD2 FOREIGN KEY (FKNOMBRE_PROD2)
REFERENCES PRODUCTOS (NOMBRE_PROD);

/*      PROCEDIMIENTOS ALMACENADOS      */

/*USUARIO*/

/*CREAR USUARIO*/
DELIMITER //
CREATE PROCEDURE CREAR_USUARIO(IN COD BIGINT, IN NOMB_USU VARCHAR(30), IN PASS VARCHAR (30))
BEGIN
INSERT INTO USUARIOS(CODIGO, NOMBRE_USUARIO,CONTRASENA) VALUES (COD,NOMB_USU,PASS);
END
//
DELIMITER ;

/*MODIFICAR USUARIO*/
DELIMITER //
CREATE PROCEDURE MODIFICAR_USUARIO(IN COD BIGINT, IN NOMB_USU VARCHAR(30), IN PASS VARCHAR(30))
BEGIN 
UPDATE USUARIOS SET NOMBRE_USUARIO=NOMB_USU WHERE CODIGO=COD;
UPDATE USUARIOS SET CONTRASENA=PASS WHERE CODIGO=COD;
END
//
DELIMITER ;

/*ELIMINAR USUARIO*/
DELIMITER //
CREATE PROCEDURE ELIMINAR_USUARIO(IN COD BIGINT)
BEGIN
DELETE FROM COMPRAS WHERE FKCODIGO3=COD;
DELETE FROM LISTA_DE_DESEOS WHERE FKCODIGO2=COD;
DELETE FROM VENTAS WHERE FKCODIGO1=COD;
DELETE FROM PRODUCTOS WHERE FKCODIGO=COD;
DELETE FROM USUARIOS WHERE CODIGO=COD;
END
//
DELIMITER ;

/*PRODUCTOS*/

/*INSERTAR PRODUCTO*/
DELIMITER //
CREATE PROCEDURE INSERTAR_PRODUCTO(IN NOM_PROD VARCHAR(20), IN PRE_PROD BIGINT, IN CANT_PROD BIGINT, IN DESC_PROD VARCHAR(200), IN FKCOD VARCHAR(30), IN EST VARCHAR(10))
BEGIN
INSERT INTO PRODUCTOS(NOMBRE_PROD,PRECIO_PROD,CANTIDAD_PROD,DESCRIPCION_PROD,FKCODIGO,ESTADO) VALUES (NOM_PROD,PRE_PROD,CANT_PROD,CANT_PROD,FKCOD,EST);
END
//
DELIMITER ;

/*CONSULTAR PRODUCTO*/
DELIMITER //
CREATE PROCEDURE CONSULTAR_PRODUCTOS(IN NOM_PROD VARCHAR(20))
BEGIN
SELECT NOMBRE_PROD, PRECIO_PROD, CANTIDAD_PROD, DESCRIPCION_PROD, ESTADO FROM PRODUCTOS WHERE NOM_PROD=NOMBRE_PROD;
END 
//
DELIMITER ;

/*MODIFICAR PRODUCTO*/
DELIMITER //
CREATE PROCEDURE MODIFICAR_PRODUCTO(IN NOM_PROD VARCHAR(20), IN PRE_PROD BIGINT, IN CANT_PROD BIGINT, IN DESC_PROD VARCHAR(200), IN FKCOD VARCHAR(30))
BEGIN
UPDATE PRODUCTOS SET NOMBRE_PROD=NOM_PROD WHERE FKCODIGO=FKCOD;
UPDATE PRODUCTOS SET PRECIO_PROD=PRE_PROD WHERE FKCODIGO=FKCOD;
UPDATE PRODUCTOS SET CANTIDAD_PROD=CANT_PROD WHERE FKCODIGO=FKCOD;
UPDATE PRODUCTOS SET DESCRIPCION_PROD=DESC_PROD WHERE FKCODIGO=FKCOD;
END
//
DELIMITER ;

/*ELIMINAR PRODUCTO*/
DELIMITER //
CREATE PROCEDURE ELIMINAR_PRODUCTO(IN NOM_PROD BIGINT)
BEGIN
DELETE FROM COMPRAS WHERE FKNOMBRE_PROD2=NOM_PROD;
DELETE FROM LISTA_DE_DESEOS WHERE FKNOMBRE_PROD1=NOM_PROD;
DELETE FROM VENTAS WHERE FKNOMBRE_PROD=NOM_PROD;
DELETE FROM PRODUCTOS WHERE NOMBRE_PROD=NOM_PROD;
END
//
DELIMITER ;

/*VENTAS*/

/*CONSULTAR VENTAS*/
DELIMITER //
CREATE PROCEDURE CONSULTAR_VENTAS(IN FKCOD VARCHAR(30))
BEGIN
SELECT FKCODIGO1, NUM_VENTA, FKNOMBRE_PROD FROM VENTAS WHERE FKCOD=FKCODIGO1;
END 
//
DELIMITER ;

/*WISHLIST*/

/*AÑADIR A LA WISHLIST*/
DELIMITER //
CREATE PROCEDURE ADD_WISHLIST(IN FKNOM_PROD VARCHAR(20), IN FKCOD VARCHAR(30))
BEGIN 
INSERT INTO WISHLIST(FKNOMBRE_PROD1,FKCODIGO2) VALUES (FKNOM_PROD,FKCOD);
END
//
DELIMITER ;

/*CONSULTAR WISHLIST*/
DELIMITER //
CREATE PROCEDURE CONSULTAR_WISHLIST(IN FKCOD VARCHAR(30))
BEGIN
SELECT FKCODIGO2, FKNOMBRE_PROD1, CONTADOR_ART FROM LISTA_DE_DESEOS WHERE FKCOD=FKCODIGO2;
SELECT PRECIO_PROD, DESCRIPCION_PROD, ESTADO FROM PRODUCTOS WHERE FKCOD=FKCODIGO;
END
//
DELIMITER ;

/*COMPRAS*/

/*REALIZAR COMPRA Y VENTA*/
DELIMITER //
CREATE PROCEDURE REALIZAR_COMPRA(IN FKNOM_PROD VARCHAR(20), IN FKCOD VARCHAR(30), IN CANT_VEND BIGINT)
BEGIN
INSERT INTO COMPRAS (FKNOMBRE_PROD2, FKCODIGO3) VALUES (FKNOM_PROD,FKCOD);
INSERT INTO VENTAS (FKNOMBRE_PROD, FKCODIGO1, CANTIDAD_VEND) VALUES (FKNOM_PROD,FKCOD,CANT_VEND);
END
//
DELIMITER ;

/*CONSULTAR COMPRAS*/
DELIMITER // 
CREATE PROCEDURE CONSULTAR_COMPRAS(IN FKCOD VARCHAR(30))
BEGIN
SELECT FKCODIGO3, FKNOMBRE_PROD2, CONTADOR_COMPRAS FROM COMPRAS WHERE FKCOD=FKCODIGO3;
END
//
DELIMITER ;

/*GENERALES*/

/*DESHACER CAMBIOS*/
DELIMITER //
CREATE PROCEDURE DESHACER()
BEGIN
    ROLLBACK;
    SELECT 'Se desharan los cambios...';
END;
//
DELIMITER ;

/*CONFIRMAR CAMBIOS*/
DELIMITER //
CREATE PROCEDURE CONFIRMACION()
BEGIN
    COMMIT;
    SELECT 'Operacion realizada con exito...';
END;
//
DELIMITER ;


CALL CREAR_USUARIO('1000719773','BRAYAN VERGARA','PITOS');
SELECT * FROM USUARIOS;

CALL MODIFICAR_USUARIO('1000719773','STEVEN VERGARA','PITOS1');
SELECT * FROM USUARIOS;

CALL INSERTAR_PRODUCTO('ARDUIO', '50000', '2', 'DESCRIPCION PERRONA', '1000719773', 'DISPONIBLE');
SELECT * FROM PRODUCTOS;

CALL MODIFICAR_PRODUCTO('ARDUINO', '45000', '1','DESCRIPCION PERRONA 2', '1000719773');

CALL CONSULTAR_PRODUCTOS('ARDUINO');

CALL REALIZAR_COMPRA('ARDUINO', '1000719773', '1');

CALL CONSULTAR_VENTAS('1000719773');

CALL CONSULTAR_WISHLIST('1000719773');

CALL CONSULTAR_COMPRAS('1000719773');

CALL ELIMINAR_USUARIO('1000719773');
SELECT * FROM USUARIOS;

CALL ELIMINAR_PRODUCTO('ARDUINO');
SELECT * FROM PRODUCTOS;